/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type Guid, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Item}
 */
// @ts-ignore
export function createItemFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoItem;
}
/**
 * The deserialization information for the current model
 * @param Item The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoItem(item: Partial<Item> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "id": n => { item.id = n.getGuidValue(); },
        "name": n => { item.name = n.getStringValue(); },
        "status": n => { item.status = n.getEnumValue<ItemStatus>(ItemStatusObject); },
    }
}
export interface Item extends AdditionalDataHolder, Parsable {
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The status property
     */
    status?: ItemStatus | null;
}
export type ItemStatus = (typeof ItemStatusObject)[keyof typeof ItemStatusObject];
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param Item The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeItem(writer: SerializationWriter, item: Partial<Item> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!item || isSerializingDerivedType) { return; }
    writer.writeGuidValue("id", item.id);
    writer.writeStringValue("name", item.name);
    writer.writeEnumValue<ItemStatus>("status", item.status);
    writer.writeAdditionalData(item.additionalData);
}
export const ItemStatusObject = {
    Draft: "Draft",
    Active: "Active",
    Archived: "Archived",
} as const;
/* tslint:enable */
/* eslint-enable */
